"""test

Revision ID: 4bf873ec75e4
Revises: d1cc2e3c8ab1
Create Date: 2024-11-14 16:25:41.168635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf873ec75e4'
down_revision = 'd1cc2e3c8ab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
