"""Initial migration

Revision ID: 91212c301dbf
Revises: 
Create Date: 2024-11-14 15:14:05.634277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91212c301dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
