"""Changed mobile_no column type from INT to BIGINT

Revision ID: d087cb5705af
Revises: 9e4606fee581
Create Date: 2024-12-06 17:17:12.276128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd087cb5705af'
down_revision = '9e4606fee581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
