"""test

Revision ID: d1cc2e3c8ab1
Revises: 91212c301dbf
Create Date: 2024-11-14 16:04:43.066050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cc2e3c8ab1'
down_revision = '91212c301dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
